name: sample_pubspec
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/dart_in_the_shell
description: A sample application
environment:
  sdk: '>=1.0.0'
dependencies:
  args: '>=0.9.0'
  bot_io: '>=0.25.0'
  logging: '>=0.9.0'
